# Ansible Inventory (hosts.ini) - simplified to 5 router hosts

[all:vars]
ansible_user=ansible
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
timezone=UTC

[routers]
router1 ansible_user=admin ansible_password=cisco ansible_host=10.0.15.61
router2 ansible_host=10.0.15.62
router3 ansible_host=10.0.15.63
router4 ansible_host=10.0.15.64
router5 ansible_host=10.0.15.65
